services:
  - type: web
    name: crypto-news-mcp-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: NEWS_API_KEY
        sync: false # Set this in the Render dashboard for security 